<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>json</string>
	</array>
	<key>name</key>
	<string>JSON (Vorhees Theme)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>((?&lt;=^\s.)|(?&lt;=[,]\s)|(?&lt;=[,])|(?&lt;=^)|(?&lt;=[:])|(?&lt;=[:]\s))(\{)|((?&lt;=^)|(?&lt;![,]\s))(\})</string>
			<key>name</key>
			<string>json.object.bracket</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[\s*$|^\s*\])</string>
			<key>name</key>
			<string>json.array.bracket</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((?&lt;=")\s*:\s*)((?=")|(?=\{)|(?=\[)|(?=(\d|\btrue\b|\bfalse\b)))</string>
			<key>name</key>
			<string>json.punctuation.colon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\\n)</string>
			<key>name</key>
			<string>json.escaped.newline</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\/)</string>
			<key>name</key>
			<string>json.path.slash</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\/)[\w -]+(?=\.j)</string>
			<key>name</key>
			<string>json.path.file.name</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\/)\w+</string>
			<key>name</key>
			<string>json.path</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b.(json|jpg|jpeg|png|exr|js|py|php)\b)</string>
			<key>name</key>
			<string>json.path.file.end</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=^\s")\w+(?="\s*:\s(\{))</string>
			<key>name</key>
			<string>json.string.nested</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=^\s")\w+(?="\s*:\s(\[))</string>
			<key>name</key>
			<string>json.string.array</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=")[^"]+(?="\s*:\s)</string>
			<key>name</key>
			<string>json.string</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=")[^"*]+((?="\s*,)|(?="$))</string>
			<key>name</key>
			<string>json.string.value</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\d)</string>
			<key>name</key>
			<string>json.number</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(null|false|true)\b)</string>
			<key>name</key>
			<string>json.boolean</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((?&lt;=\[.\n)\w+(?=\n.\]))</string>
			<key>name</key>
			<string>json.array.value</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s\*)([\w .]+)(?=\*[\s|\S])</string>
			<key>name</key>
			<string>markdown.italic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s\[)([\w .]+)(?=\][\s|\S])</string>
			<key>name</key>
			<string>markdown.link</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s\*)([\w .]+)(?=\*[\s|\S])</string>
			<key>name</key>
			<string>markdown.italic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s\*\*)([\w .]+)(?=\*\*[\s|\S])</string>
			<key>name</key>
			<string>markdown.bold</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\s)\*|\*(?!\s)</string>
			<key>name</key>
			<string>markdown.asterisks</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[\:\w+\:\])</string>
			<key>name</key>
			<string>custom.categories</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\s)\]|\[(?!\s)</string>
			<key>name</key>
			<string>markdown.brackets.angular</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.json</string>
	<key>uuid</key>
	<string>66f26404-deb2-4955-bcdd-f7855904f0c1</string>
</dict>
</plist>
